import { theme } from '../../styles/theme';

/** Общие inline-стили для справочников (Этап 1 MVP), в духе UserManager/MeetingContext. */
export const dirStyles: Record<string, React.CSSProperties> = {
  container: { display: 'flex', flexDirection: 'column', gap: 14 },
  toolbar: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    flexWrap: 'wrap' as const,
  },
  header: { display: 'flex', alignItems: 'center', gap: 8 },
  dot: { width: 6, height: 6, borderRadius: '50%', background: theme.accent.amber, flexShrink: 0 },
  title: {
    fontFamily: theme.font.heading,
    fontWeight: 700,
    fontSize: 12,
    letterSpacing: '0.12em',
    textTransform: 'uppercase' as const,
    color: theme.text.primary,
  },
  list: { display: 'flex', flexDirection: 'column', gap: 8 },
  item: {
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    padding: '12px 14px',
    background: theme.bg.tertiary,
    borderRadius: 8,
    border: `1px solid ${theme.border.default}`,
  },
  itemMain: { flex: 1, minWidth: 0 },
  itemName: { fontSize: 13, fontWeight: 600, color: theme.text.primary, fontFamily: theme.font.body },
  itemMeta: {
    fontSize: 11,
    color: theme.text.muted,
    fontFamily: theme.font.mono,
    marginTop: 2,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  label: {
    fontSize: 10,
    fontFamily: theme.font.mono,
    color: theme.accent.amber,
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
  },
  input: {
    padding: '9px 12px',
    background: theme.bg.input,
    border: `1px solid ${theme.border.default}`,
    borderRadius: 7,
    color: theme.text.primary,
    fontSize: 13,
    fontFamily: theme.font.body,
    outline: 'none',
  },
  select: {
    padding: '9px 12px',
    background: theme.bg.input,
    border: `1px solid ${theme.border.default}`,
    borderRadius: 7,
    color: theme.text.primary,
    fontSize: 13,
    fontFamily: theme.font.body,
    outline: 'none',
  },
  btn: {
    padding: '8px 14px',
    background: theme.accent.amber,
    border: 'none',
    borderRadius: 6,
    color: '#080A0F',
    cursor: 'pointer',
    fontSize: 11,
    fontFamily: theme.font.mono,
    fontWeight: 700,
    letterSpacing: '0.04em',
  },
  btnGhost: {
    padding: '6px 12px',
    background: 'transparent',
    border: `1px solid ${theme.border.amber}`,
    borderRadius: 6,
    color: theme.accent.amber,
    cursor: 'pointer',
    fontSize: 11,
    fontFamily: theme.font.mono,
    fontWeight: 500,
    letterSpacing: '0.04em',
  },
  btnDanger: {
    padding: '6px 10px',
    background: 'transparent',
    border: `1px solid ${theme.accent.red}`,
    borderRadius: 6,
    color: theme.accent.red,
    cursor: 'pointer',
    fontSize: 10,
    fontFamily: theme.font.mono,
    fontWeight: 600,
  },
  formCard: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
    padding: 16,
    background: theme.bg.card,
    border: `1px solid ${theme.border.default}`,
    borderRadius: 10,
  },
  formRow: { display: 'flex', gap: 8, flexWrap: 'wrap' as const, alignItems: 'flex-end' },
  error: { color: theme.accent.red, fontFamily: theme.font.mono, fontSize: 11 },
  empty: { color: theme.text.muted, fontFamily: theme.font.mono, fontSize: 12, padding: '8px 0' },
};
